name: Julia packages

on:
  pull_request:
    paths:
      - scripts/packages/[!VSCode]*
      - scripts/packages/[!VSCode]*/*
      - scripts/packages/[!VSCode]*/**
      - scripts/environments/languageserver/*
      - scripts/environments/languageserver/**
      - scripts/testenvironments/debugadapter/*
      - scripts/testenvironments/debugadapter/**
      - scripts/testenvironments/vscodedebugger/*
      - scripts/testenvironments/vscodedebugger/**
      - scripts/testenvironments/vscodeserver/*
      - scripts/testenvironments/vscodeserver/**
    branches:
      - main
  check_run:
    types: [rerequested, requested_action]
  push:
    branches:
      - main
  workflow_dispatch:
  workflow_call:

concurrency:
  group: ${{ github.head_ref || github.ref_name || github.run_id }} julia
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  test:
    name: test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        julia_version: ['1.0', '1.1', '1.2', '1.3', '1.4', '1.5', '1.6', '1.7', '1.8', '1.9', '1.10']
        isPR:
          - ${{github.event_name == 'pull_request'}}
        exclude:
          - isPR: true
        include:
          - julia_version: '1.0'
            os: 'ubuntu-latest'
          - julia_version: '1.6'
            os: 'ubuntu-latest'
          - julia_version: '1.10'
            os: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{matrix.julia_version}}
      - name: 'Run the Julia tests'
        run: |
          julia -e 'using InteractiveUtils; versioninfo()'
          julia --project=./scripts/environments/languageserver/v${{matrix.julia_version}} -e 'using Pkg; Pkg.resolve()'
          julia --project=./scripts/environments/languageserver/v${{matrix.julia_version}} -e 'using Pkg; Pkg.test("CSTParser", coverage=true)'
          julia --project=./scripts/environments/languageserver/v${{matrix.julia_version}} -e 'using Pkg; Pkg.test("JSONRPC", coverage=true)'
          julia --project=./scripts/environments/languageserver/v${{matrix.julia_version}} -e 'using Pkg; Pkg.test("LanguageServer", coverage=true)'
          julia --project=./scripts/environments/languageserver/v${{matrix.julia_version}} -e 'using Pkg; Pkg.test("StaticLint", coverage=true)'
          julia --project=./scripts/environments/languageserver/v${{matrix.julia_version}} -e 'using Pkg; Pkg.test("SymbolServer", coverage=true)'
          julia --project=./scripts/environments/languageserver/v${{matrix.julia_version}} -e 'using Pkg; Pkg.test("TestItemDetection", coverage=true)'
          julia --project=./scripts/testenvironments/debugadapter/v${{matrix.julia_version}} -e 'using Pkg; Pkg.test("DebugAdapter", coverage=true)'
          julia --project=./scripts/testenvironments/vscodedebugger/v${{matrix.julia_version}} -e 'using Pkg; Pkg.test("VSCodeDebugger", coverage=true)'
          julia --project=./scripts/testenvironments/vscodeserver/v${{matrix.julia_version}} -e 'using Pkg; Pkg.test("VSCodeServer", coverage=true)'
